version: '3.5'

volumes: 
  imast-mysql-volume: 
    name: imast-mysql-volume
  imast-mongo-data-volume:
    name: imast-mongo-data-volume
  imast-mongo-logs-volume:
    name: imast-mongo-logs-volume


networks:
  imastnetwork:
    name: imastnetwork

services:  

  mysqlcluster:
    image: mysqlcluster
    restart: always
    build: ./mysqlcluster
    container_name: mysqlcluster
    env_file: ./mysqlcluster/cred.env
    ports:
      - '8810:8810'
    networks:
      - imastnetwork
    volumes:
      - imast-mysql-volume:/var/lib/mysql
      
  mongoctl:
    image: mongoctl
    restart: always
    build: ./mongoctl
    container_name: mongoctl
    env_file: ./mongoctl/cred.env
    ports:
      - '8809:8809'
    networks:
      - imastnetwork
    volumes:
      - imast-mongo-data-volume:/data/db
      - imast-mongo-logs-volume:/data/logs

  controller:
    image: controller  
    build: ./controller
    container_name: controller
    ports:
      - '8801:8801'
    networks:
      - imastnetwork
    depends_on:
      - mongoctl
      
  worker-super:
    image: worker  
    build: ./worker
    container_name: worker
    environment:
      - IMAST_WORKER_ROLE=SUPERVISOR
    networks:
      - imastnetwork
    depends_on:
      - mysqlcluster
      
  worker:
    image: worker  
    build: ./worker
    environment:
      - IMAST_WORKER_ROLE=WORKER
    networks:
      - imastnetwork
    depends_on:
      - mysqlcluster
      


